### ISSUE TITLE
Implement Google Secrets for password storage

### ISSUE THREAD

**Issue by rebeccabilbro** [trisacrypto/directory#10]
This task involves refactoring the current password encryption and storage strategy to adopt Google Secrets for consistency across projects. Subtasks include:

- Setup
    - [x] create new project in Google Secrets
    - [x] enable API access
    - [x] get service creds
    - [x] modify `config.go` to know about service creds path
- Password Storage 
    - [x] in `server.go` ~make `Register` return pw instead of `VerifyEmail`.~ Deprecate encryption methodology in favor of storing pw in Google secrets.
    - [x] in `secret.go` in `CreateToken` add special chars
    - [x] in `secret.go` check that `Encrypt` and `Decrypt` aren't used anywhere else and if so, flag for deprecation in favor of Google secrets.
    - [x] in `secret.go` add `StorePassword` and `RetrievePassword` using the `DirectoryID` and `commonName` in the store path in Google Secrets
- Password Retrieval
    - [x] in `cert.go` on startup check that `CertMan` can connect to Google Secrets
    - [x] in `cert.go` in `submitCertificateRequest` look up pw in Google Secrets
    - [x] create `secret_test.go` create a test that first retrieves an environment variable that determines whether or not the test should run, and if it does run, tests password retrieval (note this will be the only way to test this without going through the certificate process)
- Protocol Buffers
    - [x] remove `pkcs12password` and `pkcs12signature` from `models.proto` (inside `proto/models/v1` ~which will be introduced in a forthcoming PR from @bbengfort~)

**Comment by bbengfort** [comment]
@rebeccabilbro this all looks great! one note - I'll have to update Register to return the PW instead of Verify in #12 - so you won't have to do that here. 

For development, can you use the test project that you created? I'd like to set up the production project on Friday together and keep development and prod separate.
