### ISSUE TITLE
Implement Google Secrets for Certificate Storage

### ISSUE THREAD

**Issue by rebeccabilbro** [trisacrypto/directory#11]
Related to #10, blocked by #10

This task involves updating the certificate storage mechanism to adopt Google Secrets storage for consistency across projects. Subtasks include:

- [x] ~in `cert.go` in [`downloadCertificateRequest`](https://github.com/trisacrypto/directory/blob/main/pkg/gds/certs.go#L253-L256) create a temp dir and store locally*. Temp dir should be deleted at the end of the function.~
- [x] in `cert.go` in [`downloadCertificateRequest` before the certificate request is marked as downloaded](https://github.com/trisacrypto/directory/blob/main/pkg/gds/certs.go#L270), store zipped cert in Google Secrets using `certRequestId`
- [x] After successfully storing in Google Secrets and marking CertificateRequest as Downloaded, call `defer os.Remove(path)` on the downloaded [`path`](https://github.com/trisacrypto/directory/blob/main/pkg/gds/certs.go#L266) 
- [x] Change [log message](https://github.com/trisacrypto/directory/blob/main/pkg/gds/certs.go#L277) to reflect storage in Google Secrets
- [x] Change the `context.Background` to be a shared context inside `downloadCertificateRequest` to be used for all calls to secret manager inside that function
- [x] Add test to `secret_test` that tests that you can store a cert to secret manager, and then access it, unzip it and decrypt it using the password; the test cert and test pw should be environment variables
- [x] ~in `cert.go` in [`downloadCertificateRequest`](https://github.com/trisacrypto/directory/blob/main/pkg/gds/certs.go#L280-L284) retrieve pw from google secrets & use to call `extractCertificate`~(done in #14)

*Temporary directories on pods use `tempfs`, which is an in-memory store that can [cause the pod to run out of memory](https://stackoverflow.com/questions/42963337/kubernetes-pod-running-out-of-memory-when-writing-to-a-volume-mount). We have three options:

1. Mount a volume as we're currently doing with [`getCertStorage()`](https://github.com/trisacrypto/directory/blob/main/pkg/gds/certs.go#L385) and simply treat it as a temporary dir and manage deleting things ourselves (easiest solution). However, this option will not automatically clean up if something goes wrong. 
2. Use `tempfs` and increase the memory of the pod (this will use standard golang `ioutil.TempDir`) 
3. Use `emptyDir` in the pod - this will only affect the manifests (in code, still use golang `ioutil.TempDir`)

**Comment by bbengfort** [comment]
@rebeccabilbro I've updated the issue with some links to line items, clarified the function where the work is done, and added some comments about temp directories in a pod context.

**Comment by rebeccabilbro** [comment]
Thanks @bbengfort &mdash; can you let me know which of (1,2,3) you want done from above?

**Comment by bbengfort** [comment]
I've been doing some research; I think we'll have to go with a combination of 1 and 3 since I'm not sure how to mount an emptyDir to the `/tmp` directory (or wherever `ioutil.TempDir` looks for it). That means you'll have to use `getCertStorage()` to get the path to the cert directory, then call `os.Remove` on the file when you're done with it. Instead of a real volume, I can mount an emptyDir there, which will be deleted when the pod is deleted. 

The good news is that this minimizes the amount of changes needed to get this feature off the ground.
